# Generated by Django 2.0.6 on 2019-01-28 16:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_one', models.DateField()),
                ('date_two', models.DateField(default=datetime.datetime.now, verbose_name='Дата ввода')),
                ('spent', models.IntegerField(blank=True, null=True, verbose_name='Потрачено')),
                ('saved', models.IntegerField(blank=True, null=True, verbose_name='Сэкономлено')),
                ('income', models.IntegerField(blank=True, null=True, verbose_name='Всего')),
            ],
            options={
                'verbose_name': 'Архив',
                'verbose_name_plural': 'Архив',
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название конфигурации')),
                ('income', models.IntegerField(verbose_name='Деньги в обороте')),
                ('icon', models.CharField(max_length=100, verbose_name='Иконка на главной')),
                ('color', models.CharField(max_length=20, verbose_name='Цвет иконки')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Дата ввода')),
                ('archive', models.ManyToManyField(blank=True, related_name='configuration', to='Core.Archive')),
            ],
            options={
                'verbose_name': 'План распределения бюджета',
                'verbose_name_plural': 'Планы распределения бюджета',
            },
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('detailed_comment', models.CharField(max_length=100, verbose_name='Подробный комментарий')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Время и дата')),
            ],
            options={
                'verbose_name': 'Трата',
                'verbose_name_plural': 'Траты',
            },
        ),
        migrations.CreateModel(
            name='CostCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('included_week_table', models.BooleanField(default=True, verbose_name='Включение в недельную таблицу')),
                ('max', models.IntegerField(verbose_name='Предел затраты')),
                ('cost', models.ManyToManyField(blank=True, related_name='category', to='Core.Cost', verbose_name='Траты')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='HelpText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='Позиция')),
                ('text', models.TextField(verbose_name='Пояснительный текст')),
            ],
            options={
                'verbose_name': 'Информационная система',
                'verbose_name_plural': 'Информационная система',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание действия')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Время и дата')),
            ],
            options={
                'verbose_name': 'История аккаунта',
                'verbose_name_plural': 'Истории аккаунтов',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_money', models.IntegerField(default=0, verbose_name='Свободные деньги')),
                ('configurations', models.ManyToManyField(related_name='settings', to='Core.Configuration', verbose_name='Конфигурация')),
                ('history', models.ManyToManyField(blank=True, related_name='settings', to='Core.History')),
            ],
            options={
                'verbose_name': 'Пользовательская настройка',
                'verbose_name_plural': 'Пользовательские настройки',
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название шоп-листа')),
            ],
            options={
                'verbose_name': 'Шоп-лист',
                'verbose_name_plural': 'Шоп-листы',
            },
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.BooleanField(default=False, verbose_name='Куплено, или нет')),
                ('name', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена продукта')),
                ('count', models.IntegerField(default=1, verbose_name='Количество')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.CostCategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Итем шоп-листа',
                'verbose_name_plural': 'Итемы шоп-листа',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название метки')),
                ('user', models.CharField(max_length=100, verbose_name='Пользователь')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Время и дата')),
            ],
            options={
                'verbose_name': 'Метка',
                'verbose_name_plural': 'Метки',
            },
        ),
        migrations.CreateModel(
            name='VersionControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, verbose_name='Наименование версии')),
                ('description', models.TextField(verbose_name='Описание изменений')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Версия',
                'verbose_name_plural': 'Список версий',
            },
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='item',
            field=models.ManyToManyField(blank=True, to='Core.ShoppingListItem', verbose_name='Итемы шоп-листа'),
        ),
        migrations.AddField(
            model_name='cost',
            name='tags',
            field=models.ManyToManyField(to='Core.Tags', verbose_name='Метки'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='category',
            field=models.ManyToManyField(related_name='configuration', to='Core.CostCategory', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='history',
            field=models.ManyToManyField(blank=True, related_name='plan_history', to='Core.History'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='shopping_list',
            field=models.ManyToManyField(blank=True, related_name='configuration', to='Core.ShoppingList', verbose_name='Списки покупок'),
        ),
        migrations.AddField(
            model_name='archive',
            name='archive_costs',
            field=models.ManyToManyField(blank=True, to='Core.Cost', verbose_name='Траты'),
        ),
    ]
